// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/cart" | "/checkout" | "/login" | "/orders" | "/profile" | "/register" | "/seller/dashboard" | "/seller/listings" | "/seller/listings/new" | "/trees" | "/trees/[id]"
type AppRouteHandlerRoutes = "/api/v1/auth/login" | "/api/v1/auth/me" | "/api/v1/auth/refresh" | "/api/v1/auth/register" | "/api/v1/listings" | "/api/v1/listings/[id]" | "/api/v1/listings/[id]/publish" | "/api/v1/orders" | "/api/v1/orders/[id]" | "/api/v1/orders/[id]/cancel" | "/api/v1/orders/[id]/ship" | "/api/v1/payments/create-intent" | "/api/v1/payments/webhook"
type PageRoutes = never
type LayoutRoutes = "/" | "/seller"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/api/v1/auth/login": {}
  "/api/v1/auth/me": {}
  "/api/v1/auth/refresh": {}
  "/api/v1/auth/register": {}
  "/api/v1/listings": {}
  "/api/v1/listings/[id]": { "id": string; }
  "/api/v1/listings/[id]/publish": { "id": string; }
  "/api/v1/orders": {}
  "/api/v1/orders/[id]": { "id": string; }
  "/api/v1/orders/[id]/cancel": { "id": string; }
  "/api/v1/orders/[id]/ship": { "id": string; }
  "/api/v1/payments/create-intent": {}
  "/api/v1/payments/webhook": {}
  "/cart": {}
  "/checkout": {}
  "/login": {}
  "/orders": {}
  "/profile": {}
  "/register": {}
  "/seller": {}
  "/seller/dashboard": {}
  "/seller/listings": {}
  "/seller/listings/new": {}
  "/trees": {}
  "/trees/[id]": { "id": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/seller": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
